{
 "title": "Smartmon Textfile",
 "description": "Smartmon Texfile node_exporter Dashboard",
 "tags": [
  "prometheus",
  "node_exporter",
  "smartmon"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": "label_values(smartmon_smartctl_version, exported_instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Smartmon All Disks",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "count(smartmon_device_info{exported_instance=~\"$instance\"}) without (exported_instance, exported_job, instance, job)"
    }
   ]
  },
  {
   "title": "Power On Hours",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "smartmon_power_on_hours_raw_value{exported_instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Disk Temperature",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "avg(smartmon_temperature_celsius_raw_value{exported_instance=~\"$instance\"}) by (exported_instance, disk)",
     "legendFormat": "{{exported_instance}} {{disk}}"
    }
   ]
  },
  {
   "title": "Raw Error Read Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(smartmon_raw_read_error_rate_value{exported_instance=~\"$instance\"}) by (exported_instance, disk)",
     "legendFormat": "val {{exported_instance}} {{disk}}"
    },
    {
     "expr": "avg(smartmon_spin_retry_count_raw_value{exported_instance=~\"$instance\"}) by (exported_instance, disk)",
     "legendFormat": "raw {{exported_instance}} {{disk}}"
    }
   ]
  },
  {
   "title": "Raw Error Read Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(smartmon_total_lbas_written_value{exported_instance=~\"$instance\"}) by (exported_instance, disk)",
     "legendFormat": "val {{exported_instance}} {{disk}}"
    },
    {
     "expr": "avg(smartmon_total_lbas_written_raw_value{exported_instance=~\"$instance\"}) by (exported_instance, disk)",
     "legendFormat": "raw {{exported_instance}} {{disk}}"
    }
   ]
  },
  {
   "title": "Reallocated Sectors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "smartmon_reallocated_sector_ct_raw_value{exported_instance=~\"$instance\"}",
     "legendFormat": "raw {{exported_instance}} {{disk}}"
    },
    {
     "expr": "smartmon_reallocated_sector_ct_value{exported_instance=~\"$instance\"}",
     "legendFormat": "val {{exported_instance}} {{disk}}"
    }
   ]
  },
  {
   "title": "Current Pending Sectors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "smartmon_current_pending_sector_raw_value{exported_instance=~\"$instance\"}",
     "legendFormat": "raw {{exported_instance}} {{disk}}"
    },
    {
     "expr": "smartmon_current_pending_sector_value{exported_instance=~\"$instance\"}",
     "legendFormat": "val {{exported_instance}} {{disk}}"
    }
   ]
  }
 ]
}