{
 "title": "UPS Status of ACP BK-650",
 "description": "Dashboard for single APC UPS",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "Charge Percent",
   "type": "graph",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "apcupsd_battery_charge_percent", "legendFormat": "Battery" }
   ]
  },
  {
   "title": "Time on Battery",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "format": "m",
   "valueName": "current",
   "targets": [
    {
     "expr": "apcupsd_battery_time_left_seconds / 60"
    }
   ]
  },
  {
   "title": "Line Voltage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    { "expr": "apcupsd_line_nominal_volts", "legendFormat": "Nominal" },
    { "expr": "apcupsd_line_volts", "legendFormat": "Actual" }
   ]
  },
  {
   "title": "Load Percent",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "apcupsd_ups_load_percent", "legendFormat": "Percent" }
   ]
  }
 ]
}